name: Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
