name: "Update Profile README"
run-name: "Update Profile README for ${{ github.event.repository.name }}"

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      github-token: ${{ steps.get-github-token.outputs.github-token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Assume IAM Role with defaults
        id: assume-iam-role
        uses: bitterbridge/github-actions/assume-iam-role@v0.0.36
        with:
          role-to-assume: ${{ vars.IAM_ROLE_TO_ASSUME }}

      - name: Get GitHub Token
        id: get-github-token
        uses: bitterbridge/github-actions/get-github-token@v0.0.36
        with:
          github-app-id-secret-path: ${{ vars.APP_ID_SECRET_PATH }}
          github-app-private-key-secret-path: ${{ vars.APP_PRIVATE_KEY_SECRET_PATH }}

  get-org-repos-md-ndouglas:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      base64: ${{ steps.get-org-repos-md.outputs.base64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Org Repos Markdown
        id: get-org-repos-md
        uses: ./.github/actions/get-org-repos-md
        with:
          owner: 'ndouglas'
          github-token: ${{ needs.setup.outputs.github-token }}

  get-org-repos-md-bitterbridge:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      base64: ${{ steps.get-org-repos-md.outputs.base64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Org Repos Markdown
        id: get-org-repos-md
        uses: ./.github/actions/get-org-repos-md
        with:
          owner: 'bitterbridge'
          github-token: ${{ needs.setup.outputs.github-token }}

  get-org-repos-md-goldentooth:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      base64: ${{ steps.get-org-repos-md.outputs.base64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Org Repos Markdown
        id: get-org-repos-md
        uses: ./.github/actions/get-org-repos-md
        with:
          owner: 'goldentooth'
          github-token: ${{ needs.setup.outputs.github-token }}

  get-org-repos-md-hellholt:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      base64: ${{ steps.get-org-repos-md.outputs.base64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Org Repos Markdown
        id: get-org-repos-md
        uses: ./.github/actions/get-org-repos-md
        with:
          owner: 'hellholt'
          github-token: ${{ needs.setup.outputs.github-token }}

  format-profile-readme:
    runs-on: ubuntu-latest
    needs:
      - setup
      - get-org-repos-md-ndouglas
      - get-org-repos-md-bitterbridge
      - get-org-repos-md-goldentooth
      - get-org-repos-md-hellholt
    steps:
      - name: Format Webring Markdown
        id: format-webring-md
        uses: bitterbridge/github-actions/format-webring-md@v0.0.36
        with:
          owner: 'bitterbridge'
          repo: '.github'

      - name: Encode substitutions
        id: encode-substitutions
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              ndouglas_repositories: `${{ needs.get-org-repos-md-ndouglas.outputs.base64 }}`,
              bitterbridge_repositories: `${{ needs.get-org-repos-md-bitterbridge.outputs.base64 }}`,
              goldentooth_repositories: `${{ needs.get-org-repos-md-goldentooth.outputs.base64 }}`,
              hellholt_repositories: `${{ needs.get-org-repos-md-hellholt.outputs.base64 }}`,
              webring: `${{ steps.format-webring-md.outputs.base64 }}`,
            });

      - name: Render Profile Template
        id: render-profile-template
        uses: bitterbridge/github-actions/render-profile-template@v0.0.36
        with:
          owner: 'ndouglas'
          repo: 'ndouglas'
          path: 'README.md.template'
          substitutions: ${{ steps.encode-substitutions.outputs.result }}

      - name: Write Profile README
        id: write-profile-readme
        uses: bitterbridge/github-actions/write-profile-readme@v0.0.36
        with:
          github-token: ${{ needs.setup.outputs.github-token }}
          owner: 'ndouglas'
          repo: 'ndouglas'
          content: ${{ steps.render-profile-template.outputs.markdown }}
          path: 'README.md'
